source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MRLCircleChart_Example' do
  pod 'MRLCircleChart', :path => '../'
end

target 'MRLCircleChart_Tests' do
  pod 'MRLCircleChart', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
