source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MRLCircleChart_Example' do
  pod 'MRLCircleChart', :path => '../'
end

target 'MRLCircleChart_Tests' do
  pod 'MRLCircleChart', :path => '../'
end
